### ISSUE TITLE
DNS changes so HTTPS works

### ISSUE THREAD

**Issue by alex** [bangbangcon/bangbangcon.github.io#115]
https://github.blog/2018-05-01-github-pages-custom-domains-https/ describes how to get HTTPS on custom domains with github pages. I think you just need to change the A records.

Thanks!

**Comment by jwise** [comment]
Although this sounds simple, I assure you that, for arcane reasons, it is not.  This has been plaguing us for years.  Maybe this will, at long last, be the year in which we update our A records.

**Comment by strugee** [comment]
http://bangbangcon.com/ seems to be redirecting to https://bangbangcon.com/ just fine - I think this should be closed?

**Comment by geekygirlsarah** [comment]
I'm going to close this as we (_finally!!_) got it fixed during !!Con 2021.
